### ISSUE TITLE
Diferença de respostas para Moedas "available"

### ISSUE THREAD

**Issue by renato-softata** [Alissonsleal/brapi#17]
A estrutura da resposta sobre a requisição https://brapi.ga/api/v2/currency/available esta diferente da requisição https://brapi.ga/api/v2/currency/available?search=BRL, por se tratar na mesma url não seria interessante ter o mesmo padrão, sugestão de retorno já utilizado como padrão:
```json
{
  "currencies": [
    {
      "name": "USD-BRL",
      "currency": "Dólar Americano/Real Brasileiro"
    },
    {
      "name": "USD-BRLT",
      "currency": "Dólar Americano/Real Brasileiro Turismo"
    },
    {
      "name": "CAD-BRL",
      "currency": "Dólar Canadense/Real Brasileiro"
    }
    ...
  ]
}
```

**Comment by Alissonsleal** [comment]
Verdade, vou puxar isso hoje mais tarde, valeu Renato.
