### ISSUE TITLE
Ativos duplicados

### ISSUE THREAD

**Issue by lucasthaynan** [Alissonsleal/brapi#24]
Ao chamar a resquisição [https://brapi.ga/api/quote/list](https://brapi.ga/api/quote/list) os ativos estão vindo todos duplicados. Como mostra o dataframe abaixo. 

![imagemapi](https://user-images.githubusercontent.com/34990294/147836075-cc788624-1df0-4deb-aa80-e8b77ef7bb46.png)

P.S.: Parabéns pelo excelento projeto! 👏🏼👏🏼

**Comment by Alissonsleal** [comment]
Subi um fix, consegue testar novamente?
