### ISSUE TITLE
API instável?

### ISSUE THREAD

**Issue by MuriloScarpaSitonio** [Alissonsleal/brapi#32]
O que está acontecendo com a API?

Estou recebendo respostas inconsistentes para múltiplos ativos. Exemplo:

https://brapi.dev/api/quote/COGN3,MGLU3,WEGE3,OIBR3 está retornando `{"error":"Não encontramos a ação OIBR3"}`
https://brapi.dev/api/quote/COGN3,MGLU3,OIBR3 está retornando `{"error":"Não encontramos a ação MGLU3"}`

**Comment by rafakwolf** [comment]
Também percebi alguma instabilidade

**Comment by lukiinhas1616** [comment]
@Alissonsleal, atualmente está ocorrendo algum problema no processamento para criptos, por exemplo, usando o default do swagger o seguinte erro é retornado:

https://brapi.dev/api/v2/crypto?coin=BTC%2CETH&currency=BRL está retornando `{"error":true,"message":"Something went wrong while fetching the data"}`

**Comment by Alissonsleal** [comment]
@lukiinhas1616 arrumado.

A yahoo finance mudou a auth de um endpoint, precisei fazer uma mudança nesse commit: https://github.com/Alissonsleal/brapi/commit/8d736d16c0a2972750631ab08eae4f7b048881ad
