### ISSUE TITLE
Date de historicalDataPrice

### ISSUE THREAD

**Issue by CarlosHenriqueDv** [Alissonsleal/brapi#39]
Esse date do historicalDatePrice está correto ?
Quando faço o parse dele, fica assim 1970-01-20T08:42:32.700+00:00
Quando faço a requisição para pegar um período maior todos vem com esse ano de 1970

![image](https://user-images.githubusercontent.com/39634892/210913152-3cc5ed8f-ac34-4ba1-be23-38f4bf633654.png)

**Comment by Alissonsleal** [comment]
Esse date é o epoch em segundos, quando você faz um `new Date(1672952700)` no javascript, é esperado em milisegundos, então aqui você vai precisar converter o epoch de segundos para milisegundos multiplicando por 1000 assim: `new Date(1672952700 * 1000)`

Site pra converter epoch para leitura humana: https://www.epochconverter.com

**Comment by CarlosHenriqueDv** [comment]
Obrigado pela resposta Alisson. Aliás, parabéns pela iniciativa e pelo trabalho.
