### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by rafakwolf** [Alissonsleal/brapi#40]
Fala Alisson.

Seguinte, já uso essa API a um bom tempo em um app react native, funciona perfeitamente.

Agora, estou fazendo alterações no app para compilar pra web tbm, porém nesse caso estou tendo erro de CORS.

A primeira coisa que fiz foi montar uma pequena api com nextJS que chama a brapi do lado servidor, já que de servidor para servidor eu não deveria ter problemas com CORS.

Ainda assim não está funcionando.

Poderia me dar um help?

Abraço!

**Comment by Alissonsleal** [comment]
A API não tem nenhuma configuração de CORS, provavelmente é alguma configuração do seu lado.
Tem alguma mensagem de erro pra debugar isso?

**Comment by rafakwolf** [comment]
Fala Alisson, valeu por responder, sim, essa msg aparece pra mim

![image](https://user-images.githubusercontent.com/2060578/216788719-ab5ce844-1195-4cf3-be09-95a739a79cfa.png)
 
O mais estranho é que o exato mesmo request de dentro do react native não da erro, esse caso ai é request de um web app.

tvz voce consiga ver log de servidor ou algo assim.

Valeu!

**Comment by rafakwolf** [comment]
Encontrei algumas coisas sobre isso, mas não sei se é válido

https://stackoverflow.com/questions/35588699/response-to-preflight-request-doesnt-pass-access-control-check

**Comment by Alissonsleal** [comment]
Paramos de usar esse domínio `.ga` faz um bom tempo, tenta usar o domínio correto `https://brapi.dev`

**Comment by rafakwolf** [comment]
resolveu com o domínio .dev, obrigado
