### ISSUE TITLE
dividendsData com dados duplicados.

### ISSUE THREAD

**Issue by lukiinhas1616** [Alissonsleal/brapi#50]
Olá!
Diversos ativos estão com dados de proventos duplicados, abaixo um exemplo do trecho da resposta.

``
    {
            "assetIssued": "BRGOAUACNOR1",
            "paymentDate": "2023-05-30T00:00:00.000Z",
            "rate": 0.05,
            "relatedTo": "1º Trimestre/2023",
            "approvedOn": "2023-04-28T00:00:00.000Z",
            "isinCode": "BRGOAUACNOR1",
            "label": "DIVIDENDO",
            "lastDatePrior": "2023-05-15T00:00:00.000Z",
            "remarks": ""
          },
          {
            "assetIssued": "BRGOAUACNOR1",
            "paymentDate": "2023-05-30T00:00:00.000Z",
            "rate": 0.25,
            "relatedTo": "1º Trimestre/2023",
            "approvedOn": "2023-04-28T00:00:00.000Z",
            "isinCode": "BRGOAUACNOR1",
            "label": "JRS CAP PROPRIO",
            "lastDatePrior": "2023-05-15T00:00:00.000Z",
            "remarks": ""
          },
          {
            "assetIssued": "BRGOAUACNPR8",
            "paymentDate": "2023-05-30T00:00:00.000Z",
            "rate": 0.05,
            "relatedTo": "1º Trimestre/2023",
            "approvedOn": "2023-04-28T00:00:00.000Z",
            "isinCode": "BRGOAUACNPR8",
            "label": "DIVIDENDO",
            "lastDatePrior": "2023-05-15T00:00:00.000Z",
            "remarks": ""
          },
          {
            "assetIssued": "BRGOAUACNPR8",
            "paymentDate": "2023-05-30T00:00:00.000Z",
            "rate": 0.25,
            "relatedTo": "1º Trimestre/2023",
            "approvedOn": "2023-04-28T00:00:00.000Z",
            "isinCode": "BRGOAUACNPR8",
            "label": "JRS CAP PROPRIO",
            "lastDatePrior": "2023-05-15T00:00:00.000Z",
            "remarks": ""
          },
``

**Requisição:**
https://brapi.dev/api/quote/GOAU4?range=1d&interval=1d&fundamental=true&dividends=true

Como é possível ver.
Existem 2 pagamentos na mesma data e valor para Dividendos e mais 2 pagamentos na mesma data e valor para juros sobre capital próprio.

**Comment by Alissonsleal** [comment]
Esses dados são pegos diretamente da b3
fonte: https://sistemaswebb3-listados.b3.com.br/fundsPage/main/38065012000177/GOAU/27/events
