### ISSUE TITLE
Inconsistências no retorno de dividendos.

### ISSUE THREAD

**Issue by lukiinhas1616** [Alissonsleal/brapi#51]
Olá!

Fazendo uns testes, verifiquei que frequentemente o campo DividendsData retorna vazio mesmo o ativo possuindo dados na api da brapi.

**Nessa request por exemplo:**
https://brapi.dev/api/quote/MRFG3,ITSA4,BRAP4,CMIN3,VIIA3,B3SA3,TAEE11,AMER3,COGN3,OIBR3,MXRF11,BCFF11,MGLU3,VGHF11,VGIA11,KISU11,PETR4,VALE3,PETR3,JBSS3,BTRA11,VINO11,SNCI11,GALG11,HCTR11,DEVA11,BTLG11,FNAM11,MCHF11,RBRD11,MOVI3,NTCO3,VIUR11,BRCR11,VGIR11,RZAG11,AGRO3,KLBN4,SANB3,BBAS3,CMIG4,CPLE6,ENAT3,GOAU4,SANB4,SAPR4,PSSA3,UNIP6,USIM5,VBBR3,XPCA11,XPSF11,TORD11,ABEV3,VISC11,FGAA11,OIAG11?range=1d&interval=1d&fundamental=true&dividends=true

Em alguns momentos o DEVA11 não retornou dados no cashDividends, em outros momentos o BTLG11 não retornou dados.
Eu apenas monitorei essas 2 situação, mas acredito que devem ocorrer com outros ativos também.

Fiquei com algumas dúvidas em relação a isso, agradeço se puder responder @Alissonsleal .

1 - Talvez isso esteja ocorrendo pela quantidade de ativos enviados na request, mas isso é realmente um problema? A Brapi tem um limite de ativos em um único request? Foi atingido no exemplo passado?
2 - (Sugestão) Existe a possibilidade de ser implementado um endpoint para retornar os ativos que possuem "data com" em uma data específica e se sim, poderia também existir que retornasse quando fosse dia de pagamento?
Exemplo: https://brapi.dev/api/quote/lastDatePriorStocks/$data
Exemplo: https://brapi.dev/api/quote/paymentDate/$data

Desde já, agradeço.

**Comment by lukiinhas1616** [comment]
![image](https://github.com/Alissonsleal/brapi/assets/37242437/c8f706f5-7580-49c8-a02c-6cdc1f6b2589)

**Comment by Kulessa** [comment]
Olá,

Ainda neste tema,
Nos meus testes os dividendos tem repostas diferentes para:
1. fundamental=true
2. fundamental=false 
3. (e sem o parâmetro fundamental)

Também reparei que está retornando o dividendo desta forma:
Fiz a consulta para BBDC3 e na resposta vem os dividendos de BBDC3 e BBDC4
202306=>202307
Label:JRS CAP PROPRIO
Rate:0,017249826
Value:13,380000114440918

202306=>202307
Label:JRS CAP PROPRIO
Rate:0,018974809
Value:13,380000114440918

202306=>202307
Label:JRS CAP PROPRIO
Rate:0,178997238
Value:14,65999984741211

202306=>202307
Label:JRS CAP PROPRIO
Rate:0,196896961
Value:14,65999984741211

**Comment by gustavommartins** [comment]
> Olá,
> 
> Ainda neste tema, Nos meus testes os dividendos tem repostas diferentes para:
> 
> 1. fundamental=true
> 2. fundamental=false
> 3. (e sem o parâmetro fundamental)
> 
> Também reparei que está retornando o dividendo desta forma: Fiz a consulta para BBDC3 e na resposta vem os dividendos de BBDC3 e BBDC4 202306=>202307 Label:JRS CAP PROPRIO Rate:0,017249826 Value:13,380000114440918
> 
> 202306=>202307 Label:JRS CAP PROPRIO Rate:0,018974809 Value:13,380000114440918
> 
> 202306=>202307 Label:JRS CAP PROPRIO Rate:0,178997238 Value:14,65999984741211
> 
> 202306=>202307 Label:JRS CAP PROPRIO Rate:0,196896961 Value:14,65999984741211

Me encontro com os mesmos pontos acabei criando um outro ISSUE(https://github.com/Alissonsleal/brapi/issues/59) que talvez resolva 2 problemas em 1 só
