### ISSUE TITLE
Ações - api/quot - erro nos filtros

### ISSUE THREAD

**Issue by renatotiburcio** [Alissonsleal/brapi#53]
Não está funcionando corretamente os filtros range, interval e fundamental
https://brapi.dev/api/quote/ITSA4?range=1mo&interval=1mo&fundamental=true&dividends=true

**Comment by Alissonsleal** [comment]
Atualmente esse filtro só funciona para o `historicalDataPrice`.
Ainda não foi implementado o filtro no `dividentsData`, que atualmente trás todos os dados

**Comment by renatotiburcio** [comment]
se você executar eese link irá ferificar que não aparece nada para historicalDataPrice
https://brapi.dev/api/quote/ITSA4?range=max&interval=max&fundamental=true&dividends=true

**Comment by Alissonsleal** [comment]
Arrumado nesse [commit](https://github.com/Alissonsleal/brapi/commit/77e55168c1aabda4b2973b4ce6a64242ea8ecf5e)

O problema era que `interval=max` não existe, agora adicionei uma validação para mostrar um erro caso `interval` ou `range` tenha valores não aceitos
