### ISSUE TITLE
[Sugestão] - Criar um algoritmo para código ISIN melhoria no response de dividendos

### ISSUE THREAD

**Issue by gustavommartins** [Alissonsleal/brapi#59]
Acho valido criar um algoritmo que identifique o nome da ação através do código ISIN que vem nos dividendos sabendo que o ISIN é um código padronizado:

Exemplo:  

BRITUBACNOR4 = ITUB3 sabendo que 

Os dois primeiros caracteres (BR) identificam o código do BRASIL.
Os quatro caracteres (ITUB) são alfanuméricos e identificam o emissor.
Os três caracteres (ACN) são alfanuméricos e identificam o tipo de ativo, podendo ter sequência automática na segunda posição (Sequência 1) e na terceira posição (Sequência 2) ou não ter qualquer sequência.
Os dois caracteres (OR) são alfanuméricos e identificam a espécie, quando se tratar de ações, ou representam uma sequência automática, para identificar cada emissão de título e valor mobiliário, quando se tratar de outras categorias.
O último caractere (4) é o dígito de controle.

Assim ficando: 
BR - Código Brasileiro
ITUB - Empresa
ACN - Tipo da Stock (AÇAO) caso fosse Units seria CDA (CERTIFICADO DE DEPOSITO DE AÇOES)
OR - Ação Ordinária então seria código 3 para preferenciais seria código 4
4 - Codiga verificador 

Com essas informações separadas sabemos que dá para montar um link de BRITUBACNOR4 e igual a ITUB3 no retorno dos dividendos que hoje não traz por stock e sim por ISIN code. Isso facilitaria em saber qual stock code aquele dividendo pertence se seria ITUB3 ou ITUB4.

Creio que isso facilitaria também uma solução melhor para os retornos dos dividendos montando um filtro pelo stock code pesquisado visto que hoje voce pesquisa os dividendos do ITUB3 e acaba vindo dividendos de ITUB3 e ITUB4 por exemplo.

Informações sobre os ISIN retirados do proprio site da B3: https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/consultas/mercado-a-vista/codigo-isin/sobre-codigo-isin/codigo-isin.htm

**Comment by Alissonsleal** [comment]
Bom estudo do formato de ISIN @gustavommartins , já estou implementando o algoritmo aqui. 
Ainda não consegui identificar um padrão para BDRs terminando em 34 e nem em fundos terminando em 11, nesse primeiro momento acho válido implementar somente para ações ordinárias e preferenciais mesmo

**Comment by renatotiburcio** [comment]
Para BRD

![image](https://github.com/Alissonsleal/brapi/assets/46468715/9582b96e-c166-4103-86fa-6bae8ea113b5)

agora para FIIs não sei se ajuda

![image](https://github.com/Alissonsleal/brapi/assets/46468715/54750b88-31cb-4fd2-bd4a-5944339e99eb)

**Comment by gustavommartins** [comment]
[renatotiburcio](https://github.com/renatotiburcio) achei o de BDR muito mais simples que de fundo, o problema de FII é as variações aleatórias que pode ter por exemplo a MXRF11, tem 3 códigos diferentes provavelmente isso aconteceu porque abriu subscrição por exemplo aí nesses casos fica difícil identificar quem é quem e seria legal comparar com outros FII para descobrir se existe algum padrão no código ISIN para eles, por exemplo código do fundo + CTF...
