### ISSUE TITLE
Erro no tipo de codificação

### ISSUE THREAD

**Issue by michaelycus** [Alissonsleal/brapi#61]
Venho utilizando a brapi há mais de anos. API incrível!
Entretanto, nas últimas semanas estou enfrentando uma série de problemas que estão afetando a utilização por parte dos meus clientes.
Tenho uma aplicação em **PHP Laravel**, que utiliza a biblioteca **GuzzleHttp**.
Uma requisição padrão no Laravel é feita assim:

```php
    $response = Http::get('https://brapi.dev/api/quote/BTLG11,XPML11,IRDM11');

    if ($response->ok()) {
        return $response->json();
    }
```
Algumas vezes no dia, algumas requisições apresentam o seguinte problema:
```
{
  "exception": {
  "class": "GuzzleHttp\Exception\RequestException",
  "message": "cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://brapi.dev/api/quote/BTLG11,XPML11,IRDM11,MALL11,XPLG11,PVBI11,KNCR11,JSRE11,TRXF11,MXRF11,KNCA11",
  "code": 200,
  "file": "/var/task/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211"
  }
}
```
O **erro 61** indica que o tipo de codificação não foi reconhecido.
Já atualizei o Guzzle; já tentei explicitar o tipo de codificação no cabeçalho, dessa forma:

```php
    $response = Http::withHeaders([
        'Accept-Encoding' => 'gzip, deflate',
    ])->get('quote/BTLG11,XPML11,IRDM11');
        
```
Entretanto, todo tipo de modificação que tentei acaba no mesmo resultado: as requisições funcionam bem por um tempo, até o mesmo erro acontecer de novo.

Alguma sugestão para corrigir esse problema?

**Comment by michaelycus** [comment]
Não teve jeito de resolver esse problema. Para contornar essa questão, tive que desabilitar a decodificação automática.
Vou deixar a solução caso alguém esteja passando pelo mesmo problema.

```php
   $response = Http::withHeaders([
        'decode_content' => false, // Desativa a decodificação de conteúdo
    ])->get('https://brapi.dev/api/quote/BTLG11,XPML11,IRDM11');

    if ($response->successful()) {
        return $response->json();
    } else {
        // log error
    }
```

**Comment by Alissonsleal** [comment]
Tinhamos ligado a compressão com brotli no cloudflare, desligamos isso hoje.
Se o problema continuar, avisa aqui que eu reabro a issue 
Valeu :rocket:
